### ISSUE TITLE
[0.2.1][Linux] Not working at all.

### ISSUE THREAD

**Issue by lantian** [adashen/vscode-tomcat#10]
On version 0.2.1 it is not possible to use plugin. Commands "Debug on Tomcat Server" and "Run on Tomcat Server" do nothing,

Using menu View -> Command Palette... -> New Tomcat Server (or any other) shows an error:
```
command 'tomcat.createserver' not found
```

VS Code version: Version 1.18.1
OS: Linux x64

**Comment by adashen** [comment]
@songkaiape can we try the plugin on linux to verify the result? Although we didn't include linux in the test plan.

**Comment by adashen** [comment]
@lantian Thanks for reporting the issue. Currently the tests have only been run on mac and windows. We will have a check on linux. And let you know the result

**Comment by songkaiape** [comment]
@adashen OK, I will run the test on linux and verify this issue

**Comment by lantian** [comment]
@adashen Thanks! If you will need any information - just ask.

**Comment by songkaiape** [comment]
@adashen I can repro this issue on ubuntu. Add bug label.

**Comment by adashen** [comment]
It seems a package issue. The package in market place is published and package through my windows machine. And if we use the package from linux machine, everything works fine.  We will add this into the test plan in the next end-game

**Comment by songkaiape** [comment]
Not repro in 0.3.0.
