### ISSUE TITLE
Debug options in server

### ISSUE THREAD

**Issue by shankarramr** [adashen/vscode-tomcat#115]
Is it possible to add starting web application in debug mode with right click option on the server? I know there is debug option from command palette but I have to select the war file for that. Can we add option to debug from the server right click menu that can debug deployed apps automatically?

**Comment by SummerSun** [comment]
Hi, thanks for the feedback. We just released Tomcat for VSCode 0.5.0. In this version, all war packages that deployed to a Tomcat Server will show in the sub-tree. You could find the demo in ReadMe.

So could I understand this feature as right-click the server in Tomcat Server Explorer and select a war package to debug, or, right-click the war package in the sub-tree to debug?

**Comment by shankarramr** [comment]
Hi, thanks for the response. I am using 0.5.0 and I am able to see the tree structure, which is great. Yeah an right on the server with 'debug' option in it would be great similar to 'start'.

**Comment by Thunderlemon** [comment]
+1 that would be a useful option

**Comment by SummerSun** [comment]
Released in version 0.8.0.

**Comment by shankarramr** [comment]
Hi, I just tried this new version and it works fine. But what I meant was to have options like in Eclipse where you can right click the server and start it in debug mode. This is will let the server apply the debugging option to whatever packages/wars deployed in it automatically instead of having to choose it separately. Similar to this: https://ibb.co/fKOOnS

**Comment by SummerSun** [comment]
Hi,

Thank you for the feedback. 

Right-click server to debug looks great.  But the extension supports multiple wars deployed on same tomcat server, it will be hard to automatically select one without user interactive. Plus, there might be no war packages deployed on the server at all. The debug work space folder could be easily incorrect for the selected war package too. So we add the right-click context command "Debug War Package" to help user to select the target war package to work on.

**Comment by merqrial** [comment]
A related question. If there are multiple war files on tomcat, how does the configuration work?
Currently, the breakpoints work through the files from multiple wars but nothing can be evaluated.

I am getting an error to specify project name in launch json.

I am doing just right click debug for both.
There are no entries in Launch json.

Firstly, can we have two war files being run in debug mode, if yes, how to specify configuration when there are multiple war files?

Any help would be appreciated.
