### ISSUE TITLE
Error starting static Resources

### ISSUE THREAD

**Issue by leogaona-luizalabs** [adashen/vscode-tomcat#12]
Hello,

I've installed the 0.2.1 version and I'm currently running VSCode on OSX High Sierra. When I try to run or debug the war at my Tomcat 7 I got the following error:

```
SEVERE: Error starting static Resources
java.lang.IllegalArgumentException: Document base /Users/leonardogaona/Library/Application Support/Code/User/workspaceStorage/366a44dabac5ab2859b42aa6282f9271/adashen.vscode-tomcat/tomcat/apache-tomcat-7.0.82/webapps/distribution-centers-api does not exist or is not a readable directory
```

The current war is at the `/Users/leonardogaona/workspace/distribution-centers-api` folder. Any idea of I could be doing wrong? The dir showed at the error exists and is owned by my OS user.

Regards,

**Comment by adashen** [comment]
@leogaona-luizalabs we cannot reproduce it on our OSX High Sierra environment. From the error message, it seems when running tomcat it does not has the access to  /Users/leonardogaona/Library/Application Support/Code/User/workspaceStorage/366a44dabac5ab2859b42aa6282f9271/adashen.vscode-tomcat/tomcat/apache-tomcat-7.0.82/webapps/distribution-centers-api

Can you try to new a new workspace and try again?
