### ISSUE TITLE
Honor deploy paths set in context.xml

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [adashen/vscode-tomcat#137]
This is more of a peeve than anything else. 

Say I have the following workflow
1) Add War to Tomcat
2) Deploy War

The war will automatically be deployed at $BASE/$ArtifactId even if the context is configured otherwise.

For example my project has an artifact ID of documentation-ws-1.0-SNAPSHOT . I have it set in my conext.xml as 

`<?xml version="1.0" encoding="UTF-8"?>
<Context antiJARLocking="true" path="/documentation"/>`

The WAR will still deploy to $BASE/$ArtifactId . 

This is an inconvenience for my workflow, as I rely on the path being what I set in the context. I can't imagine I'm the only one.

It's not a huge priority, but it's something to think about for future releases.

**Comment by SummerSun** [comment]
Hi, thank you for reporting the issue, could you please share more info about the issue? Such as the context.xml and tomcat version you used?

**Comment by JustAnotherSoftwareDeveloper** [comment]
Hello,

Sorry for the late response.

1) The Tomcat version used is 8.0.27

2) The context.xml, in it's entirety, is posted above. 

3) I don't seem to have a sever.xml in my war. I don't use eclipse, but I can verify that this setup is deploying to the correct path via netbeans.

**Comment by JustAnotherSoftwareDeveloper** [comment]
I looked into this issue further: I believe the issue is due to how tomcat works after reading this blog post: https://octopus.com/blog/defining-tomcat-context-paths 

From there, I believe one of the two following solutions would be optimal:

1) Support to rename WAR folders: The context is, by default determined by the name of folder in webapps. When I renamed the folder and restarted tomcat, I was able to effectively set the context. A simple right click menu item on the deployed wars allowing such a rename would go a long way in streamlining my workflow

2) Look for context.xml when initially unpacking the war: As the code stands, the war is unpacked to a folder with the same name. It should be possible to look for the context.xml, and then unpack the WAR to a folder of the appropriate name. This can get a bit tricky due to the event where paths conflict. 

Let me know what you think

**Comment by SummerSun** [comment]
@JustAnotherSoftwareDeveloper 

For the first solution, we are releasing 0.10.0 to support right-click on a web app folder to run/debug on Tomcat Server, then the rename feature is naturally supported by VS Code. You could see the details in the #201

**Comment by JustAnotherSoftwareDeveloper** [comment]
Great! Once 0.10.0 is released, I'll check if this issue is resolved and hopefully close out this issue

**Comment by JustAnotherSoftwareDeveloper** [comment]
when using the deploy from webapp folder, the context paths are honored!

**Comment by CedricOrcellet** [comment]
Is there a documentation on this feature because right now all I managed to do is renaming the war to fit the expected context path.

**Comment by JustAnotherSoftwareDeveloper** [comment]
No, I'm sorry. I wasn't big on markdown documentation when i was writing this. However, here is the PR: https://github.com/adashen/vscode-tomcat/pull/219/ . The application looks for a context.xml file in the META_INF folder, then uses the context path specified there (if any). This needs to be in the WAR (or directory structure) to work.
