### ISSUE TITLE
Error while starting tomcat server

### ISSUE THREAD

**Issue by madhanganesh** [adashen/vscode-tomcat#138]
After I added a tomcat server and start it I get following error:

Error: Could not find or load main class Support.Code.User.workspaceStorage.d334e892b2d87311581cee34126f1d79.adashen.vscode-tomcat.tomcat.apache-tomcat-9.0.0.M26

Not sure what i am missing. I changed tomcat version but no use.

**Comment by SummerSun** [comment]
HI,
Could you please provide more info about the issue you met? Like:

- VSCode Version:
- OS Version:
- Tomcat Extension Version:

Steps to Reproduce:
1.
2.

**Comment by pjsteele** [comment]
I am getting the same issue.  I know Tomcat is working because I can start in manually. 

```Error: Could not find or load main class Support.Code.User.workspaceStorage.fca6626b9fbf0bec5438b706ec308d93.adashen.vscode-tomcat.tomcat.tomcat8```

I'm using : 
- Mac High Sierra
- VS Code 1.21.0

Keep up the nice work. Thanks!!

**Comment by SummerSun** [comment]
@pjsteele @madhanganesh could you please provide the Tomcat version? And have you tried the different versions of Tomcat, does the issue repro in other tomcat versions?

**Comment by SummerSun** [comment]
Released 0.6.1 to do hotfix.
