### ISSUE TITLE
[Enhancement] If only one tomcat server start without asking which one

### ISSUE THREAD

**Issue by fcrespo82** [adashen/vscode-tomcat#150]
- VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
- OS version: Ubuntu 17.10 (Artful Aardvark) Linux x64 4.13.0-36-generic
- Tomcat Extension Version: 0.6.1

Steps to Reproduce:

1. Create only one tomcat server
2. Choose a war and click on Debug on tomcat
3. Choose Tomcat from a list (even though only one exists)
4. Tomcat start debugging the war

Expected result:
1. Create only one tomcat server
2. Choose a war and click on Debug on tomcat
3. Tomcat start debugging the war

**Comment by SummerSun** [comment]
Hi Fernando,

Thank you for the feedback. It does make sense to select the server if there is only one Tomcat Server. And it will save users click cost.

But when you select server in the drop down list, you could find that the last option may be "+ Create New Server", thus, if auto selecting the only server, that option will have no opportunity to show.

Considering this scenario, I'd like to suggest a choice for users to allow auto select server or not. 

If the answer is 'yes', then always select the only server.

If 'no', no behavior will be changed.

If 'never', users will not be bothered with the choice any more.

**Comment by fcrespo82** [comment]
Yes, that's true. But you can create servers on the Tomcat Servers panel as well. Isn't that enough in case users want more than one server?

Just throwing my 50 cents here. I love the extension and want it to grow.
