### ISSUE TITLE
Add support for vscode tasks 

### ISSUE THREAD

**Issue by Thunderlemon** [adashen/vscode-tomcat#174]
Feature request

I don't know if this is already possible or not, but it would be very nice to be able to manipulate a tomcat server from the vscode tasks, such has stopping, starting, restarting the server.

Regards,
Alex

**Comment by SummerSun** [comment]
Hi

We provide the command palate commands in vscode to manipulate the servers. You could just press F1 to search and use ```Tomcat: xxx``` commands.
