### ISSUE TITLE
Feature Request: Add indicator for war deploy

### ISSUE THREAD

**Issue by Thunderlemon** [adashen/vscode-tomcat#180]
This is mainly a cosmetic change and maybe to help see which context is running by adding a visual indicator beside the context name. 

![image](https://user-images.githubusercontent.com/13527306/39376874-2ebdfb18-4a21-11e8-9e67-386b0b07984c.png)

This would be helpful to be able to know when it failed to load.

**Comment by SummerSun** [comment]
War package is static. Whenever the server is running, the war package could be viewed in the browser. In another word, there is no running/stopping concepts for war packages. Its state goes along with the server it is deployed on.
