### ISSUE TITLE
0.3.0 Test Paln

### ISSUE THREAD

**Issue by adashen** [adashen/vscode-tomcat#19]
### Basic
- [x] Can run war package 
- [x] Can debug war package
- [x] Can link multiple tomcat instances
- [x] Can shutdown the running tomcat instance
- [x] Can delete the stopped tomcat instance
- [x] The tomcat instances can be saved in work space
- [x] Can open server.xml of selected tomcat instance
- [x] Can update the server.xml and run tomcat instance based on the modification

### From 0.3.0
- [x] Can start Tomcat from Tomcat Explorer
- [x] Can restart if server.xml is update during running
- [x] Can open in browser from Tomcat Explorer

## OS
- [x] Windows
- [x] OS X
- [x] Linux

## Reference
![README](https://github.com/adashen/vscode-tomcat/blob/master/README.md)

**Comment by songkaiape** [comment]
Below is the test result:

Bug found: #22 


Test case | Win10 x64 | Linux | Mac Sierra 10.12.4 | issue
-- | -- | -- | -- | --
Configurations | VSCode   1.19.0 x64   JDK1.8.0_151 x64 | VSCode 1.19.0   JDK1.8.0_151 | VSCode 1.19.0   JDK1.8.0_144 |  
Owner | Ruby | Barney | Barney |  
Clean install | Pass | Pass | Pass |  
Uninstall | Pass | Pass | Pass |  
Update | Pass | Pass | Pass |  
Run war package | Pass | Pass | Pass |  
debug   war package | Pass | Pass | Pass |  
link   multiple tomcat instances | Pass | Pass | Pass |  
shutdown   running tomcat instance | Pass | Pass | Pass |  
delete   the stopped tomcat instance | Pass | Pass | Pass |  
Tomcat   instance saved in work space | Pass | Pass | Pass |  
open   server.xml of selected tomcat instance | Pass | Pass | Pass |  
update   the server.xml and run tomcat instance based on the modification | Pass | Pass | Pass |  
[New]  start Tomcat from Tomcat Explorer | Pass | Pass | Pass |  
[New] restart if   server.xml is update during running | Fail | Fail | Fail | #22
[New] open in browser   from Tomcat Explorer | Pass | Pass | Pass |  


Issue | Details | WIN | LIN | MAC
-- | -- | -- | -- | --
#6 | tomcat   still running after close vscode | Not repro | Not repro | Not repro
#7 | Open   web page button will be hidden by debug button in status bar | Not repro | Not repro | Not repro
#8 | Enhancement:   Prompt user to restart when the server is running and the server.xml is saved | #22 | #22 | #22
#9 | Add   start operation to the tomcat node in explorer | No bug | No bug | No bug

**Comment by songkaiape** [comment]
Below is the test result:

Bug found： #26 

Test case | Win10 x64 | Linux | Mac Sierra 10.12.4 | issue
-- | -- | -- | -- | --
Configurations | VSCode   1.19.1 x64   JDK1.8.0_151 x64 | VSCode 1.19.1   JDK1.8.0_151 | VSCode 1.19.1   JDK1.8.0_144 |  
Owner | Ruby | Barney | Barney |  
Clean install | Pass | Pass | Pass |  
Uninstall | Pass | Pass | Pass |  
Update | Pass | Pass | Pass |  
Run war package | Pass | Pass | Pass |  
debug   war package | Pass | Pass | Pass | #26
link   multiple tomcat instances | Pass | Pass | Pass |  
shutdown   running tomcat instance | Pass | Pass | Pass |  
delete   the stopped tomcat instance | Pass | Pass | Pass |  
Tomcat   instance saved in work space | Pass | Pass | Pass |  
open   server.xml of selected tomcat instance | Pass | Pass | Pass |  
update   the server.xml and run tomcat instance based on the modification | Pass | Pass | Pass |  
[New]  start Tomcat from Tomcat Explorer | Pass | Pass | Pass |  
[New] restart if   server.xml is update during running | Pass | Pass | Pass |  
[New] open in browser   from Tomcat Explorer | Pass | Pass | Pass |  



Issue | Details | WIN | LIN | MAC
-- | -- | -- | -- | --
#6 | tomcat   still running after close vscode | Not repro | Not repro | Not repro
#7 | Open   web page button will be hidden by debug button in status bar | Not repro | Not repro | Not repro
#8 | Enhancement:   Prompt user to restart when the server is running and the server.xml is saved | No bug | No bug | No bug
#9 | Add   start operation to the tomcat node in explorer | No bug | No bug | No bug
