### ISSUE TITLE
When there is only one server, "tomcat start:"didn't have the selection to make user to create a new one

### ISSUE THREAD

**Issue by songkaiape** [adashen/vscode-tomcat#195]
- VSCode Version: 1.23.1
- OS Version: Mac,Win10,Linux
- Tomcat Extension Version:
0.9.0
Steps to Reproduce:

1. create a tomcat server
2. F1, select Tomcat: Start Tomcat Server 

Expect:
User always has option to create a new tomcat server when run command "Tomcat: Start Tomcat Server" from command platte
Actuall:
![image](https://user-images.githubusercontent.com/4318793/40471708-0a32e44e-5f6a-11e8-90a6-68df10c28fca.png)

**Comment by SummerSun** [comment]
close as design
