### ISSUE TITLE
Could you force Tomcat`s stop?

### ISSUE THREAD

**Issue by AndreySyagrovskiy** [adashen/vscode-tomcat#196]
- VSCode Version: 1.23.1
- OS Version: Linux Ubuntu 16.04
- Tomcat Extension Version: 0.9.0

Thank you for your extensions

We have some project which is partially is local and partially remotely and maybe that why it does not stop when I ask your extension to stop tomcat. I need to kill it myself.
Could you add the feature which kills tomcat`s process if tomcat does not stop for some time?

pache-tomcat-8.5.24-1]: [18/05/25@15:46:15.852+0300] INFO     org.apache.catalina.core.StandardServer:  A valid shutdown command was received via the shutdown port. Stopping the Server instance.
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.853+0300] INFO     org.apache.coyote.http11.Http11NioProtocol:  Pausing ProtocolHandler ["http-nio-8080"]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.904+0300] INFO     org.apache.coyote.ajp.AjpNioProtocol:  Pausing ProtocolHandler ["ajp-nio-8009"]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.955+0300] INFO     org.apache.catalina.core.StandardService:  Stopping service [Catalina]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.980+0300] INFO     org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/qad-webshell]:  Destroying Spring FrameworkServlet 'qad-webshell-servlet'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.980+0300] INFO     org.springframework.web.context.support.XmlWebApplicationContext:  Closing WebApplicationContext for namespace 'qad-webshell-servlet-servlet': startup date [Fri May 25 15:44:19 EEST 2018]; parent: Root WebApplicationContext
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.988+0300] INFO     org.springframework.context.support.DefaultLifecycleProcessor:  Stopping beans in phase 2147483647
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.990+0300] INFO     org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler:  Stopping...
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.991+0300] INFO     org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler:  BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.992+0300] INFO     org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler:  Stopped.
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.994+0300] INFO     org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor:  Shutting down ExecutorService 'brokerChannelExecutor'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.995+0300] INFO     org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler:  Shutting down ExecutorService 'messageBrokerTaskScheduler'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.999+0300] INFO     org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor:  Shutting down ExecutorService 'clientOutboundChannelExecutor'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:16.000+0300] INFO     org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor:  Shutting down ExecutorService 'clientInboundChannelExecutor'
[apache-tomcat-8.5.24-1]: Destroy Spark session...
[apache-tomcat-8.5.24-1]: INFO  com.qad.webshell.util.QadLogbackConfigurer:  Shutting down Logback logging

**There process of stoping freezes**

Kind regards, Andrii

**Comment by SummerSun** [comment]
What is the output when you stop tomcat server from the extension? Did it complete successfully? Or, what is the error message?

**Comment by AndreySyagrovskiy** [comment]
Currently is output like this:

pache-tomcat-8.5.24-1]: [18/05/25@15:46:15.852+0300] INFO org.apache.catalina.core.StandardServer: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.853+0300] INFO org.apache.coyote.http11.Http11NioProtocol: Pausing ProtocolHandler ["http-nio-8080"]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.904+0300] INFO org.apache.coyote.ajp.AjpNioProtocol: Pausing ProtocolHandler ["ajp-nio-8009"]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.955+0300] INFO org.apache.catalina.core.StandardService: Stopping service [Catalina]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.980+0300] INFO org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/qad-webshell]: Destroying Spring FrameworkServlet 'qad-webshell-servlet'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.980+0300] INFO org.springframework.web.context.support.XmlWebApplicationContext: Closing WebApplicationContext for namespace 'qad-webshell-servlet-servlet': startup date [Fri May 25 15:44:19 EEST 2018]; parent: Root WebApplicationContext
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.988+0300] INFO org.springframework.context.support.DefaultLifecycleProcessor: Stopping beans in phase 2147483647
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.990+0300] INFO org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: Stopping...
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.991+0300] INFO org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]]
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.992+0300] INFO org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: Stopped.
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.994+0300] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor: Shutting down ExecutorService 'brokerChannelExecutor'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.995+0300] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler: Shutting down ExecutorService 'messageBrokerTaskScheduler'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:15.999+0300] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor: Shutting down ExecutorService 'clientOutboundChannelExecutor'
[apache-tomcat-8.5.24-1]: [18/05/25@15:46:16.000+0300] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor: Shutting down ExecutorService 'clientInboundChannelExecutor'
[apache-tomcat-8.5.24-1]: Destroy Spark session...
[apache-tomcat-8.5.24-1]: INFO com.qad.webshell.util.QadLogbackConfigurer: Shutting down Logback logging

There process of stoping freezes

**Comment by AndreySyagrovskiy** [comment]
Tomcat extension works fine and gives correct command for tomcat to stop but some times if tomcat gets error it should kill process I think.

**Comment by SummerSun** [comment]
The extension leverages tomcat to do all the server things. It will be risky if we force tomcat to do anything because the server is not in the extension's control.

**Comment by AndreySyagrovskiy** [comment]
I understand you, but sometimes it is more convenient to give user options. Default behaviour stills same but if you added settings it would kill tomcat.

**Comment by SummerSun** [comment]
Considering that it is the java error and it does not happen a lot, it would be more reasonable for users to choose what actions to take. Besides, it we just kill tomcat directly when meet some errors, users may have no choice to know what is wrong there. In this way, settings will probably not help that much.
