### ISSUE TITLE
Feature request: Deploy exploaded war

### ISSUE THREAD

**Issue by jcjolley** [adashen/vscode-tomcat#198]
It's all in the title

**Comment by mrjones2014** [comment]
I also really need this feature! I use webpack dev server to reload frontend changes to the exploded war directory.

**Comment by SummerSun** [comment]
Thanks for the feedback. We will discuss the feature with PM and try to include it in the next version.

**Comment by AlexanderEerenberg** [comment]
If this would be possible I can fully get rid of other IDE's and use vsc for all the project I'm working on =D

**Comment by mrjones2014** [comment]
@SummerSun any plans for this issue?

**Comment by SummerSun** [comment]
@mrjones2014 @jcjolley @AlexanderEerenberg 
Add the feature in 0.10.0 plan.

We will support right click on opened folder in vscode to deploy it to tomcat server, and will check if the folder is qualified: WEB-INF/web.xml is required. Is this sounds good to you?

**Comment by jcjolley** [comment]
That sounds great!

**Comment by mrjones2014** [comment]
@SummerSun sounds great to me
