### ISSUE TITLE
0.3.0 Endgame

### ISSUE THREAD

**Issue by adashen** [adashen/vscode-tomcat#20]
## Build
- [x] 12/21 - Bump version to 0.3.0
- [x] 12/21 - Add Change logs

## Test
- [x] 12/26~12/27 - Run test plan #4 
- [x] 12/26~12/27 - Fix bugs

## Release
- [x] Add version Tag
- [x] Merge master to develop
- [x] push to market

**Comment by songkaiape** [comment]
Test result: #19
