### ISSUE TITLE
The command "View: Show Tomcat Servers" does not match pattern "Tomcat: xx_command"

### ISSUE THREAD

**Issue by sallyur** [adashen/vscode-tomcat#205]
- VSCode Version: 1.24.1
- Tomcat Extension Version: 0.9.0
- Build: 28

Steps to Reproduce:

1. F1, open the command palette
2. Search "Tomcat"

Result:

The command "View: Show Tomcat Servers" does not match pattern "Tomcat: xx_command":
![image](https://user-images.githubusercontent.com/28860891/41692598-ad5ddf64-7533-11e8-90f5-9bcd7561a0aa.png)

**Comment by SummerSun** [comment]
revert the commit of Move Tomcat server extension as an activity bar icon, issue gone.
