### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by sallyur** [adashen/vscode-tomcat#208]
- VSCode Version: 1.24.1
- OS Version: Windows
- Build: 32

Steps to Reproduce:

1. Open a project folder
2. Run command 'Tomcat: Generate War Package from Current Folder'

Result:
No war package was generated in current folder and error in toggle developer tools:
![image](https://user-images.githubusercontent.com/28860891/42028159-16d6f758-7afe-11e8-914c-10f0d018b506.png)

**Comment by SummerSun** [comment]
#210
