### ISSUE TITLE
Error message is inaccurate when changing the server port of a running server

### ISSUE THREAD

**Issue by sallyur** [adashen/vscode-tomcat#209]
- VSCode Version: 1.24.1
- OS Version: Windows
- Build: 32

Steps to Reproduce:

1.  Select one tomcat server and open the server.xml
2. Change the server port to not "8005" and save, pop up an error message
![image](https://user-images.githubusercontent.com/28860891/42029247-828b3998-7b01-11e8-8dd5-dfdfe666eacc.png)
3. Select "no" on the error message
4. Change the server port to "8005" and save, also pop up the same error message
5. If you changing the content except server port and save, still pop up the same error message

**Comment by SummerSun** [comment]
@sallyur  does this issue stable repro? I did not repro it with same bits and same vscode version in windows.

**Comment by sallyur** [comment]
I can stable repro yesterday, but today the same configuration can't stable repro. When server.xml is opened after debugging war package, sometimes it can be reproduced.

**Comment by SummerSun** [comment]
Close the issue for not stable repro.
