### ISSUE TITLE
0.10.0 End game

### ISSUE THREAD

**Issue by SummerSun** [adashen/vscode-tomcat#211]
# Build 
- [x] 7/2 - Bump version to 0.10.0 @SummerSun
- [x] 7/2 - Add CHANGELOG for 0.10.0 @SummerSun
- [x] 7/2 - Signed RC bits @songkaiape https://vscjavaci.cloudapp.net/job/vscode-tomcat.vsix-master/15/

# Test
- [x] 7/5 - Run Test Plan #202  @songkaiape 

# Release
- [x] 7/5 - Add tag 0.10.0 @SummerSun
- [x] 7/5 - Release to market place @SummerSun

**Comment by sallyur** [comment]
### Run Test Plan #202 

1. Build: 
https://vscjavaci.cloudapp.net/job/vscode-tomcat.vsix-master/ws/artifacts/16/

2. Configurations: 
Windows/Mac/Linux

3. Open bug: 
#214 #215

**Comment by SummerSun** [comment]
Issue #214  is as design.

Issue #215 is external to VSCode issue and I paste the related issue link there. Release the 0.10.0 as scheduled.
