### ISSUE TITLE
Debugging on Tomcat Server does not accept user defined breakpoints

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [adashen/vscode-tomcat#216]
- VSCode Version: 
- OS Version: Ubuntu 16.04
- Tomcat Extension Version: 0.10
-Tomcat Version: 8.0.27

Steps to Reproduce:

1. Launch a War with a tomcat server, or debug from the webapp directory
2. Set a breakpoint
3. Attempt to hit said breakpoint

Initially, I thought I wasn't connected. However, if I check "catch caught/uncaught" exceptions and run my webapp in a way that I'll hit an exception, I can step through that code.

I seem to recall being able to debug on vscode-tomcat in the past, so I believe this is a regression. However, I don't know off the top of my head on how to revert to .9 to test this. 

Unfortunately, I cannot upload the WAR, but let me know if you need more information

**Comment by SummerSun** [comment]
@JustAnotherSoftwareDeveloper Please provide the VSCode Version for us to investigate

**Comment by JustAnotherSoftwareDeveloper** [comment]
It turned out to be a misconfiguration. However, that might lead to a bigger, separate, issue. Let me investigate...

**Comment by JustAnotherSoftwareDeveloper** [comment]
closing this issue
