### ISSUE TITLE
Can't add Tomcat server on linux

### ISSUE THREAD

**Issue by FancyBanana** [adashen/vscode-tomcat#226]
- VSCode Version: 1.27.2
- OS Version: Kubuntu 18.4
- Tomcat Extension Version: 0.10.1

Steps to Reproduce:

1. Add tomcat server
2. select `/usr/share/tomcat8`  
3. Error appears: Please make sure you select a valid Tomcat Directory.

**Comment by SummerSun** [comment]
@FancyBanana As the error message indicates, the tomcat directory that is going to be added is not valid. Could you share the content of the tomcat8 folder?

**Comment by FancyBanana** [comment]
I solved the issue by installing tomcat manually (extracting archive downloaded from official site.)

**Comment by bursauxa** [comment]
@SummerSun The repository version does have conf/server.xml and conf/web.xml files, it's just that they are located in a different place (usually `/var/lib/tomcat8`). It's the difference between `$CATALINA_HOME` and `$CATALINA_BASE`.

**Comment by bursauxa** [comment]
PS. I do not know why github says I unassigned you ⁉️

**Comment by alejnp** [comment]
In Fedora 31, with Tomcat 9 installed, I cannot add `/usr/share/tomcat/` [1] from VSC either. I'll try with a user, local installation of Tomcat.

[1]: The output os `ls -l` is:
```console
$ ls -l /usr/share/tomcat
total 4
drwxr-xr-x. 2 root root   4096 oct  8 19:37 bin
lrwxrwxrwx. 1 root tomcat   11 sep 26 20:44 conf -> /etc/tomcat
lrwxrwxrwx. 1 root tomcat   22 sep 26 20:44 lib -> /usr/share/java/tomcat
lrwxrwxrwx. 1 root tomcat   15 sep 26 20:44 logs -> /var/log/tomcat
lrwxrwxrwx. 1 root tomcat   22 sep 26 20:44 temp -> /var/cache/tomcat/temp
lrwxrwxrwx. 1 root tomcat   23 sep 26 20:44 webapps -> /var/lib/tomcat/webapps
lrwxrwxrwx. 1 root tomcat   22 sep 26 20:44 work -> /var/cache/tomcat/work
```

```console                                                                                    
$ ls -l /etc/tomcat
total 244
drwxrwxr-x. 3 root tomcat   4096 sep 26 20:44 Catalina
-rw-r--r--. 1 root tomcat  12873 sep 26 20:44 catalina.policy
-rw-r--r--. 1 root tomcat   7243 sep 26 20:44 catalina.properties
drwxr-xr-x. 2 root tomcat   4096 oct  8 19:37 conf.d
-rw-r--r--. 1 root tomcat   1400 sep 26 20:44 context.xml
-rw-rw-r--. 1 root tomcat   1149 sep 26 20:44 jaspic-providers.xml
-rw-rw-r--. 1 root tomcat   2313 sep 26 20:44 jaspic-providers.xsd
-rw-r--r--. 1 root tomcat   4144 sep 26 20:44 logging.properties
-rw-r--r--. 1 root tomcat   7513 sep 26 20:44 server.xml
-rw-r--r--. 1 root tomcat   1828 sep 26 20:44 tomcat.conf
-rw-r-----. 1 root tomcat   2639 sep 26 20:44 tomcat-users.xml
-rw-rw-r--. 1 root tomcat   2633 sep 26 20:44 tomcat-users.xsd
-rw-r--r--. 1 root tomcat 172362 sep 26 20:44 web.xml

```

**Comment by aaronfranke** [comment]
Same thing on my computer, it's not recognized. I can confirm that `server.xml` and `web.xml` are both present inside of the `/usr/share/tomcat8/conf` folder.

**Comment by AnnoyedUnicorn** [comment]
Same problem here on Arch Linux, with tomcat8 and 9, installed from the official Arch repositories.
But it works when I download tomcat manually.

**Comment by shao-wang-me** [comment]
My issue was caused by file permission. My user doesn't have access to the `conf` folder. So not an issue of the extension. Also, some issues similar to this: #266, #283.

**Comment by DeathPoem** [comment]
I solved problem by useing remote setting.

```
{
    "tomcat.workspace": "/root/tomcatVscode"
}
```

**Comment by procodike** [comment]
select the directory from usr/libexec
