### ISSUE TITLE
Extension version 0.11.1 no longer respecting META-INF/context.xml

### ISSUE THREAD

**Issue by gmowhiz** [adashen/vscode-tomcat#234]
- VSCode Version: 1.29.1
- OS Version: macOS mojave 10.14.1 (18B75)
- Tomcat Extension Version: 0.11.1

Steps to Reproduce:
In version 0.11.0 of the extension, a new feature was added to support the designation of the deployment context in the META-INF/context.xml file. This appears to be broken in version 0.11.1 of the extension (at least it is for me).
1. Build a project with a META-INF/context.xml file that contains the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<Context path=""/>
```

2. Build your project.

3. Validate that META-INF/context.xml is present in the generated war or output directory.

4. Right-click and select "Debug on Tomcat Server" for either the generated `<projectName>.war` or the `target/<projectName>` output directory.

5. Confirm that Tomcat is launched but the app was deployed to the `<projectName>` context rather than the root context as was defined in the context.xml.

6. This worked for me in 0.11.0 of vscode-tomcat but is not working in 0.11.1. The workaround is to revert back to the previous extension version.

**Comment by Eskibear** [comment]
fixed in 0.12.1
