### ISSUE TITLE
Debug/Run war has no effect

### ISSUE THREAD

**Issue by leslie-Novade** [adashen/vscode-tomcat#246]
- VSCode Version: 1.33.0
- OS Version: Windows 10
- Tomcat Extension Version: 0.11.1

Steps to Reproduce:

1. Install JDK
2. Set JAVA_HOME
3. Download Tomcat
4. Install Extension + dependencies
5. Restart VSCode
6. Add tomcat server
7. Start tomcat server
8. Run/Debug war

Nothing happens.
Is there any configuration I have missed ?

Thanks

Leslie

**Comment by njneer** [comment]
Agree same issue.

**Comment by leslie-Novade** [comment]
Hi guys,

I managed to solve the issue.
It was actually due to maven not being installed and configured.

Here are the steps to fix : 
1. Install jdk
2. set JAVA_HOME and PATH
3. install tomcat
4. install & configure maven 
4. Add extensions & dependencies
5. Retart VS Code
6. Add tomcat server
7. start tomcat
8. Run / Debug war file

Thanks
