### ISSUE TITLE
[Mac,Linux]debug on tomcat will fail if you have debug it before 

### ISSUE THREAD

**Issue by songkaiape** [adashen/vscode-tomcat#26]
Repro steps:
1. right click war package, click "debug on tomcat"
2. open the app url and wait for the breakpoint hit
3. click disconnect to stop debug and stop tomcat in tomcat explore
4.  right click war package, click "debug on tomcat" again.
5. error occured
![image](https://user-images.githubusercontent.com/4318793/34248402-e8105922-e670-11e7-8653-75a4c5ad3bcb.png)

**Comment by adashen** [comment]
Please verified with https://vscjavaci.cloudapp.net/job/vscode-tomcat.vsix/7/Azure/

**Comment by songkaiape** [comment]
Not repro with  https://vscjavaci.cloudapp.net/job/vscode-tomcat.vsix/7/Azure/ .
