### ISSUE TITLE
Run in specified tomcat folder, not in the half-copy in my user directory

### ISSUE THREAD

**Issue by jeffrpowell** [adashen/vscode-tomcat#265]
- VSCode Version: 1.37.0
- OS Version: Windows_NT x64 10.0.17134
- Tomcat Extension Version: 0.11.1

I would really prefer you modify and run out of the tomcat folder that I specified when adding a tomcat server, not try to make a copy of it in the %USERPROFILE%\Roaming\Code folder. I frequently tweak my custom setenv.bat file to get different java opts in place (which you currently don't capture when you copy), mess with apps that have the empty context (which conflict with your "Open war package homepage in browser" default app), and add libraries to the tomcat lib folder.

**Comment by jaapspiering** [comment]
This duplicates the proposed solution in #224

**Comment by jeffrpowell** [comment]
Thanks for pointing that out. I agree, 224 would suffice for my concern.
