### ISSUE TITLE
[Enhancement] Changing server port throw error when tomcat sever is running

### ISSUE THREAD

**Issue by songkaiape** [adashen/vscode-tomcat#28]
Repro step:
change shutdown port when tomcat server is running throw error like blow.
And tomcat server can't be shutdown.
change this port when tomcat is shutdown ,everything is good .
![image](https://user-images.githubusercontent.com/4318793/34430327-d0be47fa-ec9e-11e7-9fc9-0f19724d676d.png)

![image](https://user-images.githubusercontent.com/4318793/34430294-872a9706-ec9e-11e7-9864-d70c989e3f96.png)
![image](https://user-images.githubusercontent.com/4318793/34430300-928a4204-ec9e-11e7-8626-f0fba14a0e23.png)

**Comment by SummerSun** [comment]
Will fix it by not allow users to update server port when the server is running
