### ISSUE TITLE
New to java - is there a project template I could use to run a servlet?

### ISSUE THREAD

**Issue by dazinator** [adashen/vscode-tomcat#301]
I'd like to cretae a vanilla servlet project that I can debug in VS Code.
However I am new to Java.
I tried creating a new java project with VS Code installed and "ready" for java development (sdk installed etc etc) and I can create a "Maven" based new project using the webapp architype. I can also add a Tom Cat server using this extension. However if I attempt to add a `.java` class for the servlet I just get vs code telling me my java class isn't on the classpath:

![image](https://user-images.githubusercontent.com/3176632/85396827-54045980-b54a-11ea-881c-33fcdc053f9b.png)

I know this is going to be obvious to any java developer, but I am a .net guy, and this terminology is completely different lingo. If there was a working project I could clone somewhere that would really help me get off the ground.

**Comment by andxu** [comment]
hi @dazinator, if you are new to java, the vscode and [java extension pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) are very suitable for you,  you can ask questions [here](https://github.com/Microsoft/vscode-java-pack), my teammate will answer your question, for Servlet, it is a very old technology I can hardly give you the classic example, but I found that this repo: https://github.com/ligado/hello-world-servlet can show the basic usage. 
```
git clone https://github.com/ligado/hello-world-servlet
cd hello-world-servlet 
mvn package
code .
````

![image](https://user-images.githubusercontent.com/17075863/86006501-a234c380-ba48-11ea-9c80-337e4b9398c7.png)

choose the `helloworld.war` in `target` folder
![image](https://user-images.githubusercontent.com/17075863/86006832-225b2900-ba49-11ea-81d2-80836c047082.png)


set a breakpoint in `HelloWorldServlet.java` and visit `http://localhost:8080/helloworld/hello` and you will be able to debug it.
![image](https://user-images.githubusercontent.com/17075863/86006701-f344b780-ba48-11ea-9cdf-ee7881a24e30.png)

**Comment by dazinator** [comment]
@andxu - thank you, much appreciated!
