### ISSUE TITLE
The Debug On Tomcat server does not work in the new version.

### ISSUE THREAD

**Issue by taeyoonkim** [adashen/vscode-tomcat#330]
- VSCode Version:
- OS Version:
- Tomcat Extension Version:

Steps to Reproduce:

The Debug On Tomcat server does not work in the new version.

**Comment by jingum** [comment]
VSCode Version: 1.61.2
OS Version:11.6 (20G165)
Tomcat Extension Version: 9.0.52
Steps to Reproduce:
1. install java env on Mac
2. install Tomcat for Java for vscode
3. Add Tomcat in vscode IDE
4. Select war and right click select 'run on tomcat'
5. do not any log in terminal and not any warmming

The Debug On Tomcat server does not work in the new version.

**Comment by Eskibear** [comment]
duplicate with #329 , please try https://github.com/adashen/vscode-tomcat/issues/329#issuecomment-954362583 and let me know if that works.
