### ISSUE TITLE
Cannot add server under remote ssh to a linux server (Debian Buster)

### ISSUE THREAD

**Issue by zachary-wang12** [adashen/vscode-tomcat#337]
- VSCode Version: 1.64.2 (local) Unknown, but should be the newest (remote)
- OS Version: Windows_NT x64 10.0.18363 (local) debian 10.11 (remote)
- Tomcat Extension Version: v0.12.1
- Tomcat Version: 9.0.58

Steps to Reproduce:

1. Install tomcat as binary archive under `/opt/apache-tomcat-9.0.58` where the folder structure and permissions are shown below:

    ```
    drwxr-xr-x 9 root   tomcat  4096 Feb 16 22:11 .
    drwxr-xr-x 7 root   root    4096 Feb 16 11:02 ..
    drwxr-x--- 2 root   tomcat  4096 Feb 11 23:15 bin
    -rw-r----- 1 root   tomcat 18970 Jan 15 22:37 BUILDING.txt
    drwx------ 3 root   tomcat  4096 Feb 16 22:44 conf
    -rw-r----- 1 root   tomcat  6210 Jan 15 22:37 CONTRIBUTING.md
    drwxr-x--- 2 root   tomcat  4096 Feb 11 23:15 lib
    -rw-r----- 1 root   tomcat 57092 Jan 15 22:37 LICENSE
    drwxr-x--- 2 tomcat tomcat  4096 Feb 16 22:27 logs
    -rw-r----- 1 root   tomcat  2333 Jan 15 22:37 NOTICE
    -rw-r----- 1 root   tomcat  3378 Jan 15 22:37 README.md
    -rw-r----- 1 root   tomcat  6898 Jan 15 22:37 RELEASE-NOTES
    -rw-r----- 1 root   tomcat 16507 Jan 15 22:37 RUNNING.txt
    drwxr-x--- 2 tomcat tomcat  4096 Feb 11 23:15 temp
    drwxr-x--- 7 tomcat tomcat  4096 Jan 15 22:37 webapps
    drwxr-x--- 3 tomcat tomcat  4096 Feb 16 22:27 work
    ```

2. Configure a new instance in `~/tomcat_vscode` where the folder structure and permissions are shown below. (user1 has added into the group tomcat).

    ```
    drwxr-xr-x  8 user1 user1 4096 Feb 17 15:43 .
    drwxr-xr-x 14 user1 user1 4096 Feb 17 16:23 ..
    drwxr-xr-x  2 user1 user1 4096 Feb 17 16:00 bin
    drwx------  3 user1 user1 4096 Feb 17 15:26 conf
    drwxr-x---  2 user1 user1 4096 Feb 17 15:59 logs
    drwxr-x---  2 user1 user1 4096 Feb 17 15:29 temp
    drwxr-x---  7 user1 user1 4096 Feb 17 15:28 webapps
    drwxr-x---  3 user1 user1  4096 Feb 17 15:29 work
    ```

3. Configure the env variables in ~/.profile:

    ```
    export JAVA_HOME=/path/to/java/home
    export CATALINA_HOME=/opt/apache-tomcat-9.0.58
    export CATALINA_BASE=/home/user1/tomcat_vscode
    ```

4. Testing start the Tomcat Server manually shows OK;

5. Add the tomcat server in vscode with Tomcat for Java add-on, and the path points to: `/opt/apache-tomcat-9.0.58`

    ```
    // Error Happen!
    Error Info: Please make sure you select a valid Tomcat Directory.
    ```

I've tried to uninstall vscode-remote several times and reinstall the Tomcat, but not worked still. Does anyone know how to solve that? Thanks!

**Comment by Eskibear** [comment]
This extension has been deprecated in favor of the [Community Server Connectors](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-community-server-connector) extension.

give it a try?

**Comment by zachary-wang12** [comment]
> This extension has been deprecated in favor of the [Community Server Connectors](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-community-server-connector) extension.
> 
> 
> 
> give it a try?

Sorry for missing the deprecated info. Thanks for your remind!
