### ISSUE TITLE
Test Plan

### ISSUE THREAD

**Issue by adashen** [adashen/vscode-tomcat#4]
### Basic
- [x] Can run war package 
- [x] Can debug war package
- [x] Can link multiple tomcat instances
- [x] Can shutdown the running tomcat instance
- [x] Can delete the stopped tomcat instance
- [x] The tomcat instances can be saved in work space

### From 0.2.0
- [x] Can open server.xml of selected tomcat instance
- [x] Can update the server.xml and run tomcat instance based on the modification

## OS
- [x] Windows
- [x] OS X

## Reference
![README](https://github.com/adashen/vscode-tomcat/blob/master/README.md)

**Comment by songkaiape** [comment]
Test case | Win10 x64 | Mac Sierra 10.12.4 | issue
-- | -- | -- | --
Configurations | VSCode   1.18.1 x64   JDK1.8.0_151 x64 | VSCode 1.18.1   JDK1.8.0_144 |  
Owner | Ruby | Barney |  
Clean install | Pass | Pass |  
Uninstall | Pass | Pass |  
Update | Pass | Pass |  
Run war package | Pass | Pass |  
debug   war package | Pass | Pass |  
link   multiple tomcat instances | Pass | Pass |  
shutdown   running tomcat instance | Pass | Pass |  
delete   the stopped tomcat instance | Pass | Pass |  
Tomcat   instance saved in work space | Pass | Pass | #6 [New]
open   server.xml of selected tomcat instance | Pass | Pass |  
update   the server.xml and run tomcat instance based on the modification | Pass | Pass |
