### ISSUE TITLE
0.2.0 Endgame

### ISSUE THREAD

**Issue by adashen** [adashen/vscode-tomcat#5]
## Build
- [x] 12/6 - Bump version to 0.2.0
- [x] 12/7 - Add Change logs

## Test
- [x] 12/6~12/7 - Run test plan #4 
- [x] 12/6~12/7 - Fix bugs

## Release
- [x] Add version Tag
- [x] Merge master to develop
- [x] push to market

**Comment by songkaiape** [comment]
Below is the test result:
Issue Found: #6 


Test case | Win10 x64 | Mac Sierra 10.12.4 | issue
-- | -- | -- | --
Configurations | VSCode   1.18.1 x64   JDK1.8.0_151 x64 | VSCode 1.18.1   JDK1.8.0_144 |  
Owner | Ruby | Barney |  
Clean install | Pass | Pass |  
Uninstall | Pass | Pass |  
Update | Pass | Pass |  
Run war package | Pass | Pass |  
debug   war package | Pass | Pass |  
link   multiple tomcat instances | Pass | Pass |  
shutdown   running tomcat instance | Pass | Pass |  
delete   the stopped tomcat instance | Pass | Pass |  
Tomcat   instance saved in work space | Pass | Pass | #6
open   server.xml of selected tomcat instance | Pass | Pass |  
update   the server.xml and run tomcat instance based on the modification | Pass | Pass |
