### ISSUE TITLE
Set Tomcat Working Directory via Settings

### ISSUE THREAD

**Issue by falco467** [adashen/vscode-tomcat#58]
Hi!
Currently Tomcat seems to start with the Current Working Directory of VS Code, which is always the VS Code directory. This is usually write-protected and several servlets usually write files to the current working directory.
If there was an option to set the default Working Directory for Tomcat Startup one could set this however one needs. - Also defaulting to CATALINA_HOME (like tomcat statup.sh) would be a good default.

**Comment by adashen** [comment]
@SummerSun & @songkaiape , Good suggestion from our user.  This could be a feature improvement in the extension.

**Comment by SummerSun** [comment]
Allow user to set the workspace via settings-> "tomcat.workspace": "workspace path" in PR #86 

If no workspace set in settings, will keep using the default path.
