### ISSUE TITLE
Delete a tomcat server when the deploy process is still running throw error

### ISSUE THREAD

**Issue by songkaiape** [adashen/vscode-tomcat#75]
repro step:

 Deploy a war package (e.g  the spring boot sample project ) to a tomcat server, when the deploy process is running delete the server ,error occur.
![image](https://user-images.githubusercontent.com/4318793/35076523-dbbbdf06-fc33-11e7-9974-677192dc9319.png)

I think we may give a better error message for this issue or remind the user the deploy process is still running.

**Comment by SummerSun** [comment]
fixed in PR #78
