### ISSUE TITLE
Configure VM Options from within Plugin

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [adashen/vscode-tomcat#87]
Hello, 

I am trying out this plugin in conjunction with other java vscode tools to see if I can't cut netbeans out of my workflow. One thing that, while not mission critical, would behoove me is to be able to set options for tomcat and the JVM from within the tomcat maven plugin. This would be a lot easier for me than fiddling with setenv.sh , which doesn't really work that well for me. 

I don't know if this is ME thing or something your average user can benefit from. If the former, feel free to close out this case.

**Comment by SummerSun** [comment]
@MichaelSila Thanks for the feedback.

It looks like a very solid feature request. I will investigate how to get the options from users and combine them during starting the tomcat server.
