### ISSUE TITLE
Deploy a different war package to a tomcat server doesn't change the link on status bar

### ISSUE THREAD

**Issue by songkaiape** [adashen/vscode-tomcat#90]
Repro steps:
1. depoy a.war to a tomcat server, the link on status bar is "open a"
![image](https://user-images.githubusercontent.com/4318793/35555855-7cd8c33a-05db-11e8-8716-47181d5ca133.png)

2. depoly b.war to the same tomcat server

Expect: the link on status bar change to "open b"
Actual: the link is still "open a"

**Comment by SummerSun** [comment]
Will make this a feature: move command "open/browse <server name>" from context command to status bar when click server. And just browse server home page with all deployed war packages display.

And due to 7+ files change, will make it part of 0.6.0 plan.

**Comment by SummerSun** [comment]
resolve
